services:
  dev-db:
    image: postgres:13
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: nest
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - freecodecamp
volumes:
  pgdata:
networks:
  freecodecamp: {}
