services:
  dev-db:
    image: postgres:13
    ports:
      - "5432:5435"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: nest
    networks:
      - freecodecamp

networks:
  freecodecamp: {}
